### ISSUE TITLE
Question about CUB dataset

### ISSUE THREAD

**Issue by khawar-islam** [3neutronstar/GuidedMixup#2]
Dear @3neutronstar ,

How did you split the CUB dataset? Like `8:2` ratio, I would appreciate your prompt response as I need to conduct an experiment urgently.

Best regards,

**Comment by 3neutronstar** [comment]
Dear @khawar-islam,

As far as we know, the CUB-200-2011 dataset officially supports training and validation indices to split. We utilize them to train the CUB dataset.

Best regards,
