### ISSUE TITLE
Request for training script of Resnet-50 (Vanilla)  for fine-grained dataset CUB_200_2011, Aircraft, StandfordCar, Caltech

### ISSUE THREAD

**Issue by roy-ch** [3neutronstar/GuidedMixup#5]
I am writing to kindly request access to the train.py script that you utilized in your experiments on the fine-grained dataset. I am particularly interested in reproducing the results presented in Table 3 for the ResNet-50 vanilla model from your study.

I have attempted to train the model using the repository available at https://github.com/cyizhuo/Fine-Grained-Image-Classification/tree/main. When setting resnet-50 pretrained to True, I achieved the following test accuracies:

Dataset | acc
-- | -- | -- | -- | --
CUB-200-2011 | 86.74 
FGVC Aircraft | 93.25 
Stanford Cars | 94.09

I also have trained with setting resnet-50 pretrained = False, but the test ACC is to be
Dataset | acc
-- | -- | -- | -- | --
CUB-200-2011 | 59.1
FGVC Aircraft |  on going
Stanford Cars | 77.68

Unfortunately, none of these results align with the accuracies reported in your Table 3.

**Comment by 3neutronstar** [comment]
I hope this following commit would help. I train the resnet-50 from the scratch.

[link](https://github.com/3neutronstar/GuidedMixup/tree/2a09e97d0de3685532da317ae929fcf2cf1c7ac6)
